# Linear Algebra Basics

In Linear Algebra we typically use vectors in their elements of R<sup>n</sup> form.

For example:
$x=
\begin{Bmatrix}
1\\
2\\
3
\end{Bmatrix}
$

is a vector in R<sup>3</sup>

In [1]:
import numpy as np

In [2]:
# A 3d vector
x = np.array([[1],
              [2],
              [3]])

In [3]:
# Vector addition
x = y = np.array([[1],
                  [2],
                  [3]])
x+y

array([[2],
       [4],
       [6]])

In [4]:
# vector scalar multiplication

2*x

array([[2],
       [4],
       [6]])

## angle between vectors

In [22]:
# basically dot product of the vectors divided by their L2 norm
x, y = np.array([[1], [2]]), np.array([[5], [7]])

# here we translate the cos(theta) definition
cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))
print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos_inverse = np.arccos(cos_theta)
print(f'angle in radiants = {np.round(cos_inverse, 3)}')

degrees = cos_inverse * ((180)/np.pi)
print(f'angle in degrees = {np.round(degrees, 3)}')

cos of the angle = [[0.988]]
angle in radiants = [[0.157]]
angle in degrees = [[8.973]]


## orthogonal vectors

In [6]:
x = np.array([[1], [0]])
y = np.array([[0], [1]])

cos_theta = (x.T @ y) / (np.linalg.norm(x,2) * np.linalg.norm(y,2))

print(f'cos of the angle = {np.round(cos_theta, 3)}')

cos of the angle = [[0.]]


## solving a system of linear equations

##### TODO: add LU decomposition

In [20]:
A = np.array([[1, 3, 5],
              [2, 2, -1],
              [1, 3, 2]])
y = np.array([[-1],
              [1],
              [2]])

In [21]:
np.linalg.solve(A, y)

array([[-2.],
       [ 2.],
       [-1.]])

In [30]:
# lets try solving a system of linear equation with no possible solution (equations with equal slope)

In [31]:
A = np.array([[2, 3],
              [4, 6]])

y = np.array([[-1],
               [1]])



In [32]:
np.linalg.solve(A, y)

LinAlgError: Singular matrix